### ISSUE TITLE
I cant reach elems cuz of ordering in js file

### ISSUE THREAD

**Issue by cafoob** [dciccale/ki.js#16]
Hey; first im glad to find ur project. And i was develope ki.js by myself. Btw sorry for english. But (like always) i've a problem with addEvent or something like that i think.

  This way is working well;
````javascript
  $('button').each(function() {
    this.classList.add('example');
  });

  $('button.example').on('click', function() {
    alert('hey');
  });
````
But i was try to change these functions order it wont work. Like this;
````javascript
  $('button.example').on('click', function() {
    alert('hey');
  });

  $('button').each(function() {
    this.classList.add('example');
  });
````

Actually i figure out by myself. This events are adding only elements. If we add this event like ``.live`` with check document, i think problem will be solve. Somethink like that;

````javascript
 $(document).on('click', 'button.example', function() {
    alert('hey');
  });

or maybe new function

 $(document).live('click', 'button.example', function() {
    alert('hey');
  });
````

Can you help me?

**Comment by cafoob** [comment]
i just code it like that its working.
````javascript  
$(document).on('click', function(e) {
    $('button.example').each(function(){
      if (this == e.target) {
        console.log('hey');
      }
    });
  });
  
  $('button').each(function() {
    this.classList.add('example');
  });
````

But how can i code it like that ``$(document).on('click', 'button.example', function() {``

**Comment by dciccale** [comment]
`$(document).on('click', 'button.example', function() {` this is not supported. this is event delegation that jquery invented. however ki.js is meant to not add too much logic. but keep things simple and as native as possible.

you can still do it if you want by extending the `.on` function

**Comment by dciccale** [comment]
I recommend you using http://kimbojs.com instead which supports event delegation
