### ISSUE TITLE
Is ki.js stable? 

### ISSUE THREAD

**Issue by pwFoo** [dciccale/ki.js#18]
Read your comment about production usage.

> The code of ki.js was written for byte-saving, so I don't recommend using this script for a real application or website. It was done for fun, and the funniest part is that it actually works :)

So ki.js isn't stable enough or just no more supported?
Is [kimbo.js](http://kimbojs.com/) the successor of ki.js?

**Comment by DanielRuf** [comment]
kimbo.js looks dead, the last update there was on the 5th Oct 2015.
