### ISSUE TITLE
Use query function to improve performance?

### ISSUE THREAD

**Issue by pwFoo** [dciccale/ki.js#19]
Could be a performance improvement for production usage. 
[query function](http://ryanmorr.com/abstract-away-the-performance-faults-of-queryselectorall/)

Should be compatible to complex css selectors too.
[regexp test](http://www.regexpal.com/?fam=96821)

**Comment by tunnckoCore** [comment]
It seems regex approach introduced by the article is slower and would go more slower in newer versions.

Also #18, kimbo is slower than jQuery.

I think ki.js needs some modernizing and using some build step will make code clear and maybe smaller.

**Comment by pwFoo** [comment]
I build a extended KI.js at the moment with a regexp based query method, KI.js extensions, and comments about added... 
But it isn't optimized for code anderen performence yet...
Just a KI.js with extensions anderen gzipped size mind.
