### ISSUE TITLE
Single letter variable names are confusing

### ISSUE THREAD

**Issue by Daniel-Hug** [dciccale/ki.js#8]
With single letter variable names like `a`, `b`, etc. it's hard to tell at a glance what a section of code does. I would opt for more descriptive variable names and leave variable renaming / obfuscation to the JS minifier. Even variable names like `fn`, `cb`, `el`, `doc`, and `win` are so much easier to read, and they won't add a whole lot of bytes to your unminified files. Are you open to switching to readable variable names?

**Comment by dciccale** [comment]
This is a bit old already..
